# Generated by Django 4.2.7 on 2023-11-25 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('user_text', models.TextField()),
                ('bot_text', models.TextField()),
                ('state', models.CharField(max_length=50)),
            ],
        ),
    ]
